linters:
  LineLength:
    enabled: false
  RuboCop:
    enabled: false # TODO: resolve this
  StringQuotes:
    enabled: true
    style: double_quotes
  SpaceInsideHashAttributes:
    enabled: false
  InstanceVariables:
    enabled: true
    exclude:
      - app/views/radars/_quadrant_nav.html.haml # TODO: resolve this
      - app/views/radars/_radar.html.haml # TODO: resolve this
