linters:
  LineLength:
    enabled: false
  RuboCop:
    enabled: false # TODO: resolve this
  StringQuotes:
    enabled: true
    style: double_quotes
  SpaceInsideHashAttributes:
    enabled: false
