require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  RunRailsCops: true
  Exclude:
    - bin/*
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*.rb
    - config/initializers/devise.rb
Metrics/AbcSize:
  Exclude:
    - app/lib/thought_works_importer.rb # TODO
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Exclude:
    - app/helpers/application_helper.rb
    - app/lib/thought_works_importer.rb
Rails/Delegate:
  Exclude:
    - app/models/blip.rb # TODO
Rails/Output:
  Exclude:
    - config/initializers/analytics_ruby.rb
    - config/unicorn.rb
Style/Documentation:
  Enabled: false
Style/GuardClause:
  Exclude:
    - app/lib/thought_works_importer.rb
Style/StringLiterals:
  EnforcedStyle: double_quotes
