require: rubocop-rspec

AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*.rb
    - config/initializers/devise.rb
StringLiterals:
  EnforcedStyle: double_quotes
LineLength:
  Enabled: false
PercentLiteralDelimiters:
  Enabled: false
Documentation:
  Enabled: false
Metrics/MethodLength:
  Exclude:
    - app/helpers/application_helper.rb
    - app/lib/thought_works_importer.rb
Style/GuardClause:
  Exclude:
    - app/lib/thought_works_importer.rb
