AllCops:
  Exclude:
    - bin/rake
    - bin/rails
    - bin/spring
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*.rb
    - config/initializers/devise.rb
StringLiterals:
  Enabled: false
LineLength:
  Enabled: false
PercentLiteralDelimiters:
  Enabled: false
Documentation:
  Enabled: false
