development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: techradar_development
  pool:     5

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: techradar_test
  pool:     5
